#!/usr/bin/env python3
import os
import sys

def main():
    # Path to your virtual environment

    home_directory = os.path.expanduser("~")

    venv_path = os.path.join(home_directory,'.virtualenvs','kubectl-node-cloud')

    # Activate the virtual environment
    if sys.platform == 'win32':
        bin_dir = os.path.join(venv_path, 'Scripts')
    else:
        bin_dir = os.path.join(venv_path, 'bin')
    
    os.environ['PATH'] = bin_dir + os.pathsep + os.environ['PATH']
    os.environ['VIRTUAL_ENV'] = venv_path
    os.environ['PYTHONHOME'] = ''
    
    # Ensure that the virtual environment's Python interpreter is used
    executable = os.path.join(bin_dir, 'python')
    if not os.path.exists(executable):
        raise EnvironmentError(f"Python executable not found in virtual environment at {executable}")
    
    # Path to your main script
    main_script = os.path.join(venv_path,'bin',os.path.basename(sys.argv[0]))

    # Execute the main script using the virtual environment's Python interpreter
    os.execv(executable, [executable] + [main_script] + sys.argv[1:])

if __name__ == '__main__':
    main()
